### PR TITLE
Skip bridge gen for inline-reified decoded() (fixes #81)

### LINKED ISSUE #81: DocumentSnapshot.decoded() crashes Swift-native Android callers (regression in #80 / 0.18.0)
Any Swift-native caller on Android that invokes `DocumentSnapshot.decoded()` crashes immediately:

```
F SwiftRuntime: SkipFirebaseFirestore_Bridge.swift:2778: Fatal error: Unexpectedly found nil while unwrapping an Optional value
F DEBUG : #01 … ($s21SkipFirebaseFirestore16DocumentSnapshotC23Java_decoded_5_methodID…)
F DEBUG : #07 … ($s21SkipFirebaseFirestore16DocumentSnapshotC7decodedxyKSeRzlF+120)
```

Crash site in the auto-generated `SkipFirebaseFirestore_Bridge.swift`:

```swift
nonisolated private static let Java_decoded_5_methodID =
    Java_class.getMethodID(name: "decoded", sig: "()Ljava/lang/Object;")!
```

## Root cause

`decoded()` is declared `inline reified` via `SKIP DECLARE` (`Sources/SkipFirebaseFirestore/SkipFirebaseFirestore.swift`, ~line 1100):

```swift
// SKIP DECLARE: public inline fun <reified T : Decodable> decoded(): T
public func decoded<T: Decodable>() throws -> T { … }
```

The bridge generator emits a `getMethodID("decoded", "()Ljava/lang/Object;")!` JNI lookup, but `javap` on the compiled `DocumentSnapshot.class` shows no `decoded` method exists in bytecode:

```
public class skip.firebase.firestore.DocumentSnapshot {
    getDoc, kotlin, getDescription, equals, getDocumentID, getExists,
    data, get, Swift_projection, Swift_projectionImpl
}
```

The bridge `!` force-unwrap traps on class load.

### What triggers the bytecode elision

Not arity — adding a one-arg sibling `decoded(documentID: String?)` with the same `inline reified` declaration produces the same bytecode-elided result (tested directly: bridge entry `Java_decoded_6_methodID` gets emitted; `javap` shows neither overload in `DocumentSnapshot.class`).

The differentiator is class hierarchy. `FirestoreDecoder.decode` uses the same `inline reified` pattern and **does** land in bytecode:

```
$ javap -p FirestoreDecoder.class
public final <T extends skip.lib.Decodable> T decode(skip.lib.Dictionary<…>);
public final <T extends skip.lib.Decodable> T decode(skip.lib.Dictionary<…>, String);
```

The only structural difference: `DocumentSnapshot` has `QueryDocumentSnapshot` as a subclass; `FirestoreDecoder` has no subclasses. Kotlin inline functions can't participate in virtual dispatch, so the compiler elides the JVM-callable shim for `inline reified` methods on `open class`es that actually have subclasses, while preserving it on `open class`es without any.

**Practical implication:** Swift-native Android callers DO have a working Codable surface today — `try FirestoreDecoder().decode(from: snapshot.data()!, documentID: snapshot.documentID)`. The bridge entry and bytecode method both exist. The crash is only on the `DocumentSnapshot.decoded()` convenience wrapper. (Runtime correctness of `FirestoreDecoder.decode` for Swift-native callers is bytecode-confirmed callable but we ship a different workaround app-side and haven't runtime-tested this path end-to-end.)

## Who's affected

- **Swift-native Android callers** (consuming-app types compiled to native Swift ARM64, NOT annotated `/* SKIP @bridge */`). Calls route through the bridge → JNI lookup → crash. **Directly observed.**
- **Kotlin callers** (Skip-transpiled `.kt`, plus `@bridge`-annotated Swift) inline the body at the call site and never look up the missing method. **Unaffected.**

PR #80's checklist shows iOS sim and Android emulator boxes unchecked — only `swift test` was run, which doesn't exercise the JNI bridge layer. The author also noted that *"Skip can't bridge T.Type parameters, so on Android the Codable decode is `let m: MyModel = try snapshot.data()` (return-type inference)"* — i.e. inline-reified was chosen specifically as the T.Type workaround, without checking that Swift-native Android callers can still reach the resulting method via the bridge.

## Blast radius

Single PR (#80), single tag — `0.18.0` only. Not in `0.17.x` or `0.15.x`.

## Minimal repro

```swift
import SkipFirebaseFirestore

// On Android, called from a class NOT marked `// SKIP @bridge`:
let snapshot = try await Firestore.firestore()
    .collection("things").document("x").getDocument()
let _: MyModel = try snapshot.decoded()   // traps in SkipFirebaseFirestore_Bridge.swift:2778

struct MyModel: Codable { var name: String }
```

## Possible fixes

1. **`// SKIP @nobridge` on `decoded()`** → bridge gen skips the broken lookup. Kotlin callers keep inlining; Swift-native callers reach `FirestoreDecoder().decode(…)` directly instead. **Verified + PR'd:** see #82 — generated `SkipFirebaseFirestore_Bridge.swift` no longer contains `Java_decoded_5_methodID` after the patch; other `DocumentSnapshot` bridge entries remain intact.
2. **Replace `inline reified` with `T.Type` parameter form** (`decode<T>(_: T.Type, from:)`). **Blocked upstream:** `swift build --target SkipFirebaseFirestore` against a local patch fails with `error: This release does not yet support bridging T.Type` from the Skip transpiler. PR #80's author chose inline-reified specifically to work around this same limitation. Not viable for Skip packages until `skiptools/skip` adds T.Type bridging.
3. **Teach the bridge generator to skip method-ID lookup for inline-reified-on-subclassed-classes**, in `skiptools/skip`. Proper systemic fix; protects every Skip package using this pattern. Not tested.

## Workarounds (Swift-native Android callers)

1. **Use `FirestoreDecoder` directly** — `try FirestoreDecoder().decode(from: snapshot.data()!, documentID: snapshot.documentID)`. The bytecode/bridge entry exists today. Verbose but no app-side glue needed. Upstream-reachable.
2. **App-side `data(as: T.Type)` extension** (iOS-shaped API). Works in consuming apps because app-side Swift extensions don't go through the bridge layer — Swift→Kotlin transpilation handles everything; both legs share the same compiled output. **Validated end-to-end:** shipping in a real app, Firestore reads succeed across 28 Codable model types. Cannot be added to upstream skip-firebase (T.Type bridging blocker per fix 2 above).

## Environment

- Skip toolchain `1.9.2`
- skip-firebase `0.18.0`
- Android target: ARM64 emulator, API 34

### PR DESCRIPTION
**Pull request by vincentborko**
Fixes #81.

`DocumentSnapshot.decoded()` was declared with `// SKIP DECLARE: public inline fun <reified T : Decodable> decoded(): T`, making the Kotlin signature inline-reified. Inline-reified functions are inlined at every call site, so the compiled `.class` exposes no callable `decoded` method — but the bridge generator still emitted a `getMethodID("decoded", "()Ljava/lang/Object;")!` JNI lookup. That force-unwrap traps native-Swift Android callers (non-`@bridge` app code) the moment the `DocumentSnapshot` class loads. Kotlin / `@bridge` callers inline the body and never look it up, which is why `swift test` didn't catch it.

### Fix

Drop the `// SKIP DECLARE` and mark `decoded()` with `@inline(__always)`. Per the [Skip docs](https://skip.dev/docs/swiftsupport/#reified-types), Skip converts any `@inline(__always)` Swift function into a Kotlin `inline fun <reified T>` automatically — same reified call-site inlining (so no broken JNI lookup is emitted), but standard Swift syntax instead of a hand-written declaration that can drift from the body, and `decoded()` stays reachable for native-Swift Android callers.

```swift
@inline(__always)
public func decoded<T: Decodable>() throws -> T { … }
```

(An earlier revision of this PR used `// SKIP @nobridge`, which fixed the crash but dropped `decoded()` from the bridge surface entirely. `@inline(__always)` is strictly better — thanks @marcprux.)

### Verification

- Transpiles clean (Swift → Kotlin) with the `@inline(__always)` form.
- Relying on CI to confirm the generated `SkipFirebaseFirestore_Bridge.swift` no longer emits the `decoded` JNI lookup.

### CODE REVIEW

**Comment by vincentborko** [comment]
Follow-up note for reviewers: tried adding `DocumentSnapshot.data(as: T.Type)` upstream as the replacement Codable API for Swift-native Android callers (since this PR's `@nobridge` removes `decoded()` from their reach). The Skip toolchain rejects it: `error: This release does not yet support bridging T.Type`.

Details + reasoning in #81 (Option 2 section + issue comment). Short version: this PR remains the correct crash fix, but the API gap it creates is genuine — no upstream replacement is reachable for Swift-native Android callers until `skiptools/skip` adds T.Type bridging support, or until an API shape that avoids generics-as-parameter is designed.

**Comment by vincentborko** [comment]
Quick follow-up on the trade-off section: actually verified root cause and it's narrower than I implied. See [#81 update](https://github.com/skiptools/skip-firebase/issues/81#issuecomment-4564407987) — `FirestoreDecoder.decode` works fine for Swift-native Android callers as-is (bytecode entry exists; no inline-reified elision because `FirestoreDecoder` has no subclass). The crash is only on the `DocumentSnapshot.decoded()` convenience wrapper.

So this PR's `@nobridge` removes `decoded()` from Swift-native callers' reach but leaves them with `try FirestoreDecoder().decode(from: snapshot.data()!, documentID: snapshot.documentID)` — verbose but functional. Smaller API gap than the original trade-off text suggested.

File: Sources/SkipFirebaseFirestore/SkipFirebaseFirestore.swift [hunk 1]
```diff
@@ -1097,6 +1097,7 @@ public class DocumentSnapshot: KotlinConverting<com.google.firebase.firestore.Do
     // NOTE: use return-type inference on Android:
     //   let model: MyModel = try snapshot.decoded()
     // On iOS use FirebaseFirestoreSwift's data(as: MyModel.self) instead.
+    // SKIP @nobridge
```
Comment (marcprux) [inline Sources/SkipFirebaseFirestore/SkipFirebaseFirestore.swift]: I wonder if instead of marking this `@nobridge`, we might instead remove the `SKIP DECLARE` altogether and instead mark `decoded` with `@inline(__always)` as per https://skip.dev/docs/swiftsupport/#reified-types. I think the LLM that helped with https://github.com/skiptools/skip-firebase/pull/80 wasn't aware that we can generate reified signatures without having to fall back to `SKIP DECLARE`.

**Comment by vincentborko** [comment]
`@inline(__always)` is the better fix, keeps `decoded()` reachable for native-Swift Android callers instead of dropping it from the bridge surface like `@nobridge` did. Reworked in fa0d43d: dropped the `// SKIP DECLARE`, added `@inline(__always)` per https://skip.dev/docs/swiftsupport/#reified-types. Transpiles clean locally, CI will confirm the generated bridge no longer emits the `decoded` JNI lookup.

**Comment by marcprux** [comment]
Great! I'm glad that worked.
