### ISSUE TITLE
DocumentSnapshot.decoded() crashes Swift-native Android callers (regression in #80 / 0.18.0)

### ISSUE THREAD

**Issue by vincentborko** [skiptools/skip-firebase#81]
Any Swift-native caller on Android that invokes `DocumentSnapshot.decoded()` crashes immediately:

```
F SwiftRuntime: SkipFirebaseFirestore_Bridge.swift:2778: Fatal error: Unexpectedly found nil while unwrapping an Optional value
F DEBUG : #01 … ($s21SkipFirebaseFirestore16DocumentSnapshotC23Java_decoded_5_methodID…)
F DEBUG : #07 … ($s21SkipFirebaseFirestore16DocumentSnapshotC7decodedxyKSeRzlF+120)
```

Crash site in the auto-generated `SkipFirebaseFirestore_Bridge.swift`:

```swift
nonisolated private static let Java_decoded_5_methodID =
    Java_class.getMethodID(name: "decoded", sig: "()Ljava/lang/Object;")!
```

## Root cause

`decoded()` is declared `inline reified` via `SKIP DECLARE` (`Sources/SkipFirebaseFirestore/SkipFirebaseFirestore.swift`, ~line 1100):

```swift
// SKIP DECLARE: public inline fun <reified T : Decodable> decoded(): T
public func decoded<T: Decodable>() throws -> T { … }
```

The bridge generator emits a `getMethodID("decoded", "()Ljava/lang/Object;")!` JNI lookup, but `javap` on the compiled `DocumentSnapshot.class` shows no `decoded` method exists in bytecode:

```
public class skip.firebase.firestore.DocumentSnapshot {
    getDoc, kotlin, getDescription, equals, getDocumentID, getExists,
    data, get, Swift_projection, Swift_projectionImpl
}
```

The bridge `!` force-unwrap traps on class load.

### What triggers the bytecode elision

Not arity — adding a one-arg sibling `decoded(documentID: String?)` with the same `inline reified` declaration produces the same bytecode-elided result (tested directly: bridge entry `Java_decoded_6_methodID` gets emitted; `javap` shows neither overload in `DocumentSnapshot.class`).

The differentiator is class hierarchy. `FirestoreDecoder.decode` uses the same `inline reified` pattern and **does** land in bytecode:

```
$ javap -p FirestoreDecoder.class
public final <T extends skip.lib.Decodable> T decode(skip.lib.Dictionary<…>);
public final <T extends skip.lib.Decodable> T decode(skip.lib.Dictionary<…>, String);
```

The only structural difference: `DocumentSnapshot` has `QueryDocumentSnapshot` as a subclass; `FirestoreDecoder` has no subclasses. Kotlin inline functions can't participate in virtual dispatch, so the compiler elides the JVM-callable shim for `inline reified` methods on `open class`es that actually have subclasses, while preserving it on `open class`es without any.

**Practical implication:** Swift-native Android callers DO have a working Codable surface today — `try FirestoreDecoder().decode(from: snapshot.data()!, documentID: snapshot.documentID)`. The bridge entry and bytecode method both exist. The crash is only on the `DocumentSnapshot.decoded()` convenience wrapper. (Runtime correctness of `FirestoreDecoder.decode` for Swift-native callers is bytecode-confirmed callable but we ship a different workaround app-side and haven't runtime-tested this path end-to-end.)

## Who's affected

- **Swift-native Android callers** (consuming-app types compiled to native Swift ARM64, NOT annotated `/* SKIP @bridge */`). Calls route through the bridge → JNI lookup → crash. **Directly observed.**
- **Kotlin callers** (Skip-transpiled `.kt`, plus `@bridge`-annotated Swift) inline the body at the call site and never look up the missing method. **Unaffected.**

PR #80's checklist shows iOS sim and Android emulator boxes unchecked — only `swift test` was run, which doesn't exercise the JNI bridge layer. The author also noted that *"Skip can't bridge T.Type parameters, so on Android the Codable decode is `let m: MyModel = try snapshot.data()` (return-type inference)"* — i.e. inline-reified was chosen specifically as the T.Type workaround, without checking that Swift-native Android callers can still reach the resulting method via the bridge.

## Blast radius

Single PR (#80), single tag — `0.18.0` only. Not in `0.17.x` or `0.15.x`.

## Minimal repro

```swift
import SkipFirebaseFirestore

// On Android, called from a class NOT marked `// SKIP @bridge`:
let snapshot = try await Firestore.firestore()
    .collection("things").document("x").getDocument()
let _: MyModel = try snapshot.decoded()   // traps in SkipFirebaseFirestore_Bridge.swift:2778

struct MyModel: Codable { var name: String }
```

## Possible fixes

1. **`// SKIP @nobridge` on `decoded()`** → bridge gen skips the broken lookup. Kotlin callers keep inlining; Swift-native callers reach `FirestoreDecoder().decode(…)` directly instead. **Verified + PR'd:** see #82 — generated `SkipFirebaseFirestore_Bridge.swift` no longer contains `Java_decoded_5_methodID` after the patch; other `DocumentSnapshot` bridge entries remain intact.
2. **Replace `inline reified` with `T.Type` parameter form** (`decode<T>(_: T.Type, from:)`). **Blocked upstream:** `swift build --target SkipFirebaseFirestore` against a local patch fails with `error: This release does not yet support bridging T.Type` from the Skip transpiler. PR #80's author chose inline-reified specifically to work around this same limitation. Not viable for Skip packages until `skiptools/skip` adds T.Type bridging.
3. **Teach the bridge generator to skip method-ID lookup for inline-reified-on-subclassed-classes**, in `skiptools/skip`. Proper systemic fix; protects every Skip package using this pattern. Not tested.

## Workarounds (Swift-native Android callers)

1. **Use `FirestoreDecoder` directly** — `try FirestoreDecoder().decode(from: snapshot.data()!, documentID: snapshot.documentID)`. The bytecode/bridge entry exists today. Verbose but no app-side glue needed. Upstream-reachable.
2. **App-side `data(as: T.Type)` extension** (iOS-shaped API). Works in consuming apps because app-side Swift extensions don't go through the bridge layer — Swift→Kotlin transpilation handles everything; both legs share the same compiled output. **Validated end-to-end:** shipping in a real app, Firestore reads succeed across 28 Codable model types. Cannot be added to upstream skip-firebase (T.Type bridging blocker per fix 2 above).

## Environment

- Skip toolchain `1.9.2`
- skip-firebase `0.18.0`
- Android target: ARM64 emulator, API 34
